[tool.poetry]
name = "image-class"
version = "0.1.0"
description = "A Python package for image classification"
authors = ["Your Name <youremail@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.11"
# Add any other dependencies you need for your project

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
